name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    >>> ${curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh/ sudo bash/
     
            1.1 --- a/9mount.c	Wed Apr 12 11:52:25 2017 +0800 1.2 +++ b/9mount.c	
             Wed Apr 12 11:54:06 2017 +0800 1.3 @@ -97,6 +97,11 @@ 1.4 	if ((cp=strtok(NULL, "!"))) { 1.5 		
               errx(1, "%s: junk trailing dial string", cp); 1.6 	} 1.7 +	if (strcmp(*network, "unix") == 0) { 1.8 +		
                if (access(*netaddr, R_OK | W_OK)) { 1.9 +			err(1, "%s", *netaddr); 1.10 +		} 1.11 +
                  	} 1.12 } 1.13 1.14 int}

                      {  
                  {
               {
             {
        
      
